server:
  port: 8088

spring:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  resources:
    staticLocations: ["classpath:/META-INF/resources/", "classpath:/resources/","classpath:/static/", "classpath:/public/"]
  datasource:
    manager:
      slaves:
        - type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/avenue?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
          username: root
          password: root
          max-active: 10
          min-idle: 0
        - type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/avenue?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
          username: root
          password: root
          max-active: 10
          min-idle: 0
      master:
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/avenue?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
          username: root
          password: root
          max-active: 10
          min-idle: 0
