server:
  port: 80

spring:
  thymeleaf:
    cache: false
  resources:
    staticLocations: ["classpath:/templates/","classpath:/META-INF/resources/", "classpath:/resources/","classpath:/static/", "classpath:/public/"]
  datasource:
    manager:
      slaves:
        - type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://localhost:3306/okcoin_user_local?characterEncoding=UTF-8&amp;autoReconnect=true&amp;rewriteBatchedStatements=true&amp;userSSL=true
          username: root
          password: 123123
          max-active: 10
          min-idle: 0
        - type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://localhost:3306/okcoin_user_local?characterEncoding=UTF-8&amp;autoReconnect=true&amp;rewriteBatchedStatements=true&amp;userSSL=true
          username: root
          password: 123123
          max-active: 10
          min-idle: 0
      master:
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://localhost:3306/okcoin_user_local?characterEncoding=UTF-8&amp;autoReconnect=true&amp;rewriteBatchedStatements=true&amp;userSSL=true
          username: root
          password: 123123
          max-active: 10
          min-idle: 0
